### ISSUE TITLE
How to extract the embedded vectors for peptides/spectra?

### ISSUE THREAD

**Issue by yangkl96** [tzom/yHydra#2]
Is it possible to get the embeddings? I could modify the code to output them, but I was wondering if there was an easier way.

Thanks,
Kevin

**Comment by tzom** [comment]
hi kevin,

thanks for your question!

for the peptides, they are the result of **embed_db.py**:
e.g. if you do run the example (see **README.md**) with `python run.py ./example/config.yaml`
you should be able to find them in:
`./example/forward/db/embedded_peptides.npy` and load them with numpy.load()

regarding the spectra, those are not explicitly stored on disk, yet. However, they are created in search.py and you may go from there:
https://github.com/tzom/yHydra/blob/470c9d1389bc33a804713a2d8a8a78d6090365de/search.py#L129

If you find it useful, to have them actually saved on the disk (i.e. embedded_spectra.npy -- similar to the stored peptide embeddings above). Then let me know and i can add this to the workflow.

Hope this helps, otherwise let me know if something is missing!

**Comment by yangkl96** [comment]
Thank you! I will test things out first and let you know if spectral embedding saving would be helpful
